import "./globals.css";

export const metadata = {
  title: "Joy Amorin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="antialiased bg-background">
        {children}
      </body>
    </html>
  );
}
